export const ENV_VARS = {
  PORT: 'PORT',
  MONGO_DB_USER: 'MONGO_DB_USER',
  MONGO_DB_PASSWORD: 'MONGO_DB_PASSWORD',
  MONGO_DB_HOST: 'MONGO_DB_HOST',
  MONGO_DB_DB: 'MONGO_DB_DB',
  APP_DOMAIN: 'APP_DOMAIN',
  MAIL_TOKEN: 'MAIL_TOKEN',
  MAIL_TO: 'MAIL_TO',
  MAIL_FROM: 'MAIL_FROM',
  SENDGRID_API_KEY: 'SENDGRID_API_KEY',
};
