export const ENV_VARS = {
  PORT: 'PORT',
  MONGO_DB_USER: 'MONGO_DB_USER',
  MONGO_DB_PASSWORD: 'MONGO_DB_PASSWORD',
  MONGO_DB_HOST: 'MONGO_DB_HOST',
  MONGO_DB_DB: 'MONGO_DB_DB',
  APP_DOMAIN: 'APP_DOMAIN',
  MAIL_TOKEN: 'MAIL_TOKEN',
  TELEGRAM_TOKEN: 'TELEGRAM_TOKEN',
  TELEGRAM_CHAT_ID: 'TELEGRAM_CHAT_ID',
};
